[service]
name="defaultName"
[sendgrid]
id="daylaidmoi"
[log]
path="/data/logs"
name="utils"
level="debug"
[client]
target="localhost:1234"
[server]
port=1234
[secret]
ggdir="/Volumes/hdd/Drives/OneDrive/ssh/ggapi/"
[consul]
address="3.0.1.198:999"
interval="15s"
ttl=300
host="10.8.0.10"